# Generated by Django 2.2.6 on 2021-12-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikeList',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'like_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('userpw', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
